name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - deploy  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    # - name: Prepare Dockerfile
    #   run: cp ./backend/Dockerfile ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: imdeveshshukla/quiet-backend

    - name: Verify Pushed Image
      run: docker pull imdeveshshukla/quiet-backend

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@master  working
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       sudo docker pull imdeveshshukla/quiet-backend:latest
    #       sudo docker stop web-app || true
    #       sudo docker rm web-app || true
    #       sudo docker run --env-file .env --restart-always -d --name web-app -p 3000:3000 imdeveshshukla/quiet-backend:latest